branches:
  only:
    - 'master'
    - 'develop'

language: ruby
rvm:
  - 2.1
  - 2.0

env:
  - DB=postgresql
  - DB=mysql

before_script:
  - mysql -e 'create database enyo_test'
  - psql -c 'create database enyo_test' -U postgres

bundler_args: "--binstubs=./bundler_stubs"
script:
  - chmod +x "./script/ci/build.sh"
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake db:seed --trace
  - bundle exec rake db:test:prepare
  - rspec spec